### ISSUE TITLE
adjusting P-values

### ISSUE THREAD

**Issue by boxiangliu** [bmvdgeijn/WASP#39]
Hello Bryce and Graham, 

First of all, happy New Year! 

After running CHT on permuted data, it appears the permuted p-values don't follow null. You suggested either to manually set the overdispersion parameters or to adjust the p-values according to the permuted distribution. I have the following questions: 

1) How should I manually adjust the overdispersion parameter? I was not able to find much reference on manual parameter adjustments.

2) If going with second option, can I simply run combined_test.py N times with --shuffle flag to obtain N sets of permutation p-values as the null distribution, and calculate calibrated p-values using this null distribution? 

3) I would imagine the first option is faster, while the second option provides more accurate calibration. Which one would you recommend? 

Thank you! 
Bosh

**Comment by gmcvicker** [comment]
Hi Bosh,

Did you estimate the overdispersion parameters using the fit_as_coefficients.py and fit_bnb_coefficients.py scripts?

If you go with the first option, I would try running combined_test.py using a grid of overdispersion parameters that are within a 'reasonable' range of the estimated coefficients. The difficulty is deciding what a reasonable range is. You might try running on 1/2 or double the estimated coefficients for starters to see how this changes your distribution of p-values. You may also be able to get a sense of which overdispersion parameter is poorly estimated by running the combined_test.py separately for the AS and beta-negative-binomial (read count) tests. Ideally both components of the test should give well-calibrated p-values on their own. You can run the components separately using the --as_only and --bnb_only flags.

If you go with the second option, you would do essentially what you described--use the permuted p-values to estimate an FDR. I think it is probably only necessary to do one permutation run (you will get distribution of p-values because you are presumably testing a lot of regions), but you can do more than one if you desire (e.g. 3). I think this approach will be easier to get working, but will be a bit less powerful than if you have well-estimated dispersion parameters. 

 Hope this helps,

Graham

If using the second option.

**Comment by boxiangliu** [comment]
Hello Graham,

Sorry for the late replay - just got back from holiday travel. Thanks so much for your response! 

Yes, I estimated the overdispersion parameters using scripts provided in the package. I am not sure why the parameters are underestimated, maybe it is because of my limited sample size (10 samples)? 

For the first option, should I keep the proportions of the estimated coefficients unchanged? e.g. to change original coefficients {a1, a2, ..., a10} to {2 x a1, 2 x a2, ..., 2 x a10} and {1/2 x a1, 1/2 x a2, ..., 1/2 x a10}, etc? 

For the second option, since we are only running the permutation 1 time, is it assumed that all tested regions follow the same null distribution? Another way to ask the same question: to obtain permutation test p-values for the original data, should I pool p-values from all tested regions from the single permutation to form a null distribution? Sorry if the question sound simplistic, but it is not obvious to me how 1 permutation would be sufficient. 

Thank you, 
Bosh

**Comment by gmcvicker** [comment]
Hi Bosh,
Sorry for not replying to this earlier. I suppose the assumption from this approach is that if you generate a single p-value from each region that the resulting distribution is a good approximation to a null for the entire dataset. This assumes that regions that have more extreme p-values than they should due to overdispersion will also tend to generate more extreme p-values when permuted. Generating more permutation p-values from each region might give you a better null, but gets computationally more expensive.

Hope that helps,

Graham

**Comment by boxiangliu** [comment]
This makes a lot of sense. Thanks you! Closing issue.

**Comment by gmcvicker** [comment]
Hi Bosh,
We recently ran into an issue where the test statistics were inflated (i.e. p-values too low) because the input files provided to extract_haplotype_read_counts.py had mulitple overlapping target regions for a single test. In this case these were duplicate or partially duplicate exons representing different transcript isoforms of a gene. This can cause problems with the CHT, because it causes the allele-specific reads to be counted multiple times for the same SNP. I wonder if this could be causing some of the problems that you ran into with poorly calibrated p-values. We are working to modify the extract_haplotype_read_counts.py script to check the input files for this.

**Comment by boxiangliu** [comment]
Hi Graham,

Thanks for letting me know. It is possible that I had the same issue too. I ran CHT on the gene level rather than on the transcript level so I maybe it was not too big an issue for me. I am keen on trying the update though!
