### ISSUE TITLE
get_target_regions.py "Index out of range" error

### ISSUE THREAD

**Issue by jenkelly10** [bmvdgeijn/WASP#52]
Hi Graham,
I am having issues with get_target_regions.py script and one sample (the last one in our sample file).  Everything works fine for 24 of our 25 samples and then I get this:

individual: lgs100524
  chr1
  chr2
  chr3
  chr4
  chr5
  chr6
  chr7
  chr8
  chr9
  chr10
  chr11
  chr12
  chr13
  chr14
  chr15
  chr16
  chr17
  chr18
  chr19
  chr20
  chr21
  chr22
individual: lgs302096
  chr1
Traceback (most recent call last):
  File "/usr/local/analysis/wasp/0.2.1-a48f02c/bin/get_target_regions.py", line 495, in <module>
    main()
  File "/usr/local/analysis/wasp/0.2.1-a48f02c/bin/get_target_regions.py", line 396, in main
    combined_files.add_counts(chrom_list, count_files, snp_files, ind_idx)
  File "/usr/local/analysis/wasp/0.2.1-a48f02c/bin/get_target_regions.py", line 132, in add_counts
    a_hap = hap_tab[:, hap_a_idx]
  File "/usr/lib/python2.7/dist-packages/tables/array.py", line 647, in __getitem__
    startl, stopl, stepl, shape = self._interpret_indexing(key)
  File "/usr/lib/python2.7/dist-packages/tables/array.py", line 399, in _interpret_indexing
    raise IndexError("Index out of range")
IndexError: Index out of range
Closing remaining open files:./combined_read_count.h5...done../../HDF5_formatted_files/snp_tab.h5...done./combined_ref_count.h5...done../../Bam2h5_files/H3K4me1//alt_as_counts.lgs302096.h5...done../../HDF5_formatted_files/haplotypes.h5...done./combined_alt_count.h5...done../../HDF5_formatted_files/snp_index.h5...done./combined_het_count.h5...done../../Bam2h5_files/H3K4me1//ref_as_counts.lgs302096.h5...done../../Bam2h5_files/H3K4me1//read_counts.lgs302096.h5...done./combined_as_count.h5...done

This sample (302096) doesn't produce any errors in any of the mapping routines.  So, I thought maybe the problem was with the HDF5 SNP files (specifically the haplotype file from the error).  However, when I look at the vcf formatted genotype and haplotype files that were used to create the HDF5 SNP files, there doesn't seem to be any issue (the sample is present in the genotype and haplotype files and there seems to be sufficient information present).  

Do you have any thoughts?  What additional info can I send to you that might help"? 

Thanks so much!

**Comment by gmcvicker** [comment]
I think the most likely problem is that samples file you are providing to get_target_regions does not exactly match the samples in the VCF file that was used to create the HDF5 files. This script currently expects that the number and ordering of the samples in provided samples file be exactly the same.

With the recent code update, the sample information is now included directly in the HDF5 files, and this is what is used by the mapping part of the code to determine the correct sample index. This is a lot less error-prone than the 'old way' of requiring a separate samples file matches the sample order of the original VCF or impute file. Unfortunately I have not yet had time to update the CHT part of the code and it still uses the 'old way' to determine sample indexes. 

I will try to update the CHT code to use the sample info in the HDF5 files, but in the meantime it would be simpler to just make sure your sample ordering matches exactly. Can you provide the header of the VCF file and the samples file so that I can check this?

**Comment by jenkelly10** [comment]
Hi Graham,

Thanks so much for your reply.  Yes, I had thought of that and double checked and they look to be in the same order to me but maybe I am missing something? I have attached my unaltered sample file that I have been using as well as the headers for the geno and haplo VCF files.

Thanks so much for your help!


On Sep 27, 2016, at 4:33 PM, Graham McVicker <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the most likely problem is that samples file you are providing to get_target_regions does not exactly match the samples in the VCF file that was used to create the HDF5 files. This script currently expects that the number and ordering of the samples in provided samples file be exactly the same.

With the recent code update, the sample information is now included directly in the HDF5 files, and this is what is used by the mapping part of the code to determine the correct sample index. This is a lot less error-prone than the 'old way' of requiring a separate samples file matches the sample order of the original VCF or impute file. Unfortunately I have not yet had time to update the CHT part of the code and it still uses the 'old way' to determine sample indexes.

I will try to update the CHT code to use the sample info in the HDF5 files, but in the meantime it would be simpler to just make sure your sample ordering matches exactly. Can you provide the header of the VCF file and the samples file so that I can check this?

�

**Comment by gmcvicker** [comment]
I didn't get the attachments. Pease email them directly to my salk email or to my gmail account (gmcvicker ~a~t~ gmail)

**Comment by jenkelly10** [comment]
Graham, I sent them to your gmail account on the 28th.  If you didn't receive them, please let me know.  Thanks!

**Comment by gmcvicker** [comment]
I believe that the problem is that your samples file has a header line "samples population group", that is being interpreted as a sample name. This is resulting in an off-by-one for all of the samples, and causes the index of the last sample to be out of range. If you remove the header line I think that it will fix the problem.

This is an unfortunately error-prone aspect of the pipeline since the code expects the samples file to match the samples in the HDF5 files exactly. The HDF5 files now contain sample information and I have already changed the mapping part of the pipeline to use this. I will work on updating the CHT part of the pipeline to use the embedded sample information as well.

**Comment by jenkelly10** [comment]
Thanks so much, Graham! I should have thought about that, sorry!!!! I will try it and see. 

Thanks so much for your help and sorry for the trouble!! 

Best,

Jennifer

**Comment by jenkelly10** [comment]
That seems to have fixed my issues, Graham!  Thanks so much for your help!
