### ISSUE TITLE
Chimeric reads and filter_remapped_reads.py

### ISSUE THREAD

**Issue by anamayshetty** [bmvdgeijn/WASP#70]
I've been putting some .bam files through the WASP mapping pipeline and I have hit into a problem. When I put my remapped reads through filter_remapped_reads.py, I get the following error:

`ValueError: saw read NS500144:884:H5CMVBGX3:3:13602:8091:6268 more times than expected in input file`

It suggests that the original .bam used paired-end reads, so I re-ran the original .bam through find_intersecting_snps.py with --is_paired_end. The resting output gave two very small paired .fastqs and a single fastq file that is as large as the fastq file created when --is_paired_end was in its default single state.

After remapping using BWA mem, the .bam file from the paired ends gave the following error when put through filter_remapped_reads.py:

`keep_reads: 0
bad_reads: 0
discard_reads: 1197916`

And using the single fastq gave the same `ValueError` as before. After probing the .bam files, we did find repeated IDs:

`NS500144:884:H5CMVBGX3:3:13602:8091:6268	2064	chr11	119889737	59	35M40H	*	0	0	CTTTGACGCGTATGACAAATCCGTGAGCTCTTGGA	E/EEEEEEEAAEEEEEEEEEEEE/EEEEEEE/EEE	NM:i:1	MD:Z:21T13	AS:i:30	XS:i:0	SA:Z:chr11,119889741,-,33S42M,60,1;
NS500144:884:H5CMVBGX3:3:13602:8091:6268	16	chr11	119889741	60	33S42M	*	0	0	CTTTGACGCGTATGACAAATCCGTGAGCTCTTGGACGCGTATGACAAATCCGTGAGCTCTTGGAGTAGAAGATAA	E/EEEEEEEAAEEEEEEEEEEEE/EEEEEEE/EEEEEEE6EEEEEEEEEEEE/EEEEEEEEEEEEEEEEEAAAAA	NM:i:1	MD:Z:17T24	AS:i:37	XS:i:0	SA:Z:chr11,119889737,-,35M40S,59,1;`

We suspect that this fault is due to a chimeric read. Is this the case, and is there a way to accommodate this in the WASP pipeline?

Thanks,

Anamay

**Comment by gmcvicker** [comment]
I believe that find_intersecting_snps.py does not currently handle secondary alignments properly. I will try to fix this. In the meantime, you may want to consider using "bwa aln" rather than "bwa mem" because clipping reads is not always desirable for allele-specific analysis. The issue is that a local aligner such as 'bwa mem' will prefer to clip the read when a mismatch (i.e. alternate allele) occurs at the end of the read rather than including it in the alignment as a mismatch.

**Comment by anamayshetty** [comment]
Thank you, I will go and use bwa aln instead.
