### ISSUE TITLE
snp2h5 no longer supports matching chromosomes regardless of "chr" prefix

### ISSUE THREAD

**Issue by kwcurrin** [bmvdgeijn/WASP#75]
The most recent version of WASP (released in July 2018) no longer matches chromosomes between bam and VCF files if the "chr" prefix is present in one file but not the other. For example, "chr1" in a bam file will not match "1" in a VCF file.

**Comment by gmcvicker** [comment]
I have modified snp2h5 so that it now tries to add/remove 'chr' from the chromosome name that is read from the VCF file in order to match chromosome names read from the chromInfo file:

https://github.com/bmvdgeijn/WASP/commit/3184de35c8339ef667a4377c6daa371cc742dcc4

This change has been committed to the master branch and is also part of today's release (v0.3.1).

If you are having problems matching chromosome names elsewhere in the pipeline please let us know.

**Comment by kwcurrin** [comment]
Thanks!
